apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Documents
  annotations:
    github.com/project-slug: sj-patel/Documents
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: guests
