site_name: Documents
repo_name: 'GitHub'
repo_url: https://github.com/sj-patel/Documents
edit_uri: "edit/main/docs/"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  
plugins:
  - techdocs-core
